### ISSUE TITLE
quick question: how is text prompt dealt with ?

### ISSUE THREAD

**Issue by CoinCheung** [CompVis/cleandift#3]
Hi,

Stable diffusion is known to be a text to image generation model. It requires a text-prompt to generate an image. In terms of model architecture, it usually uses block like cross qkv attention to inject text semantic into the model. Here with cleandift, it accepts only an image as input and outputs image features, with model structure same as SD2.1. So would you please tell me how did you deal with the part of  text-embedding ?

**Comment by stefan-baumann** [comment]
Typically, for many tasks, one just conditions on a somewhat fitting prompt, e.g., "a photo of a dog" (see our semantic correspondence example notebook here: https://github.com/CompVis/cleandift/blob/main/notebooks/get_correspondences.ipynb). You can also generally just condition on an empty prompt, although it will typically be a bit worse than conditioning on a proper prompt.

For completeness, I should also mention the approach introduced by ODISE (https://jerryxu.net/ODISE/), which some methods have adopted. Here, they condition on a combination of the embedding of an empty prompt and the CLIP _image_ embedding of the clean image, using a learned interpolation weight vector. You can see this here: https://github.com/NVlabs/ODISE/blob/2b187e4b2ff4c3d5da342aec2cc234b537720a65/odise/modeling/meta_arch/ldm.py#L705-L709. This approach has been adopted by A Tale of Two Features and Telling Left from Right. See also Appendix E, "CLIP Image Embedding Conditioning" in our preprint for more details.

**Comment by CoinCheung** [comment]
@stefan-baumann Thanks for telling me this！Will it be reasonable if I set a prompt of "a photo of a dog" for all of the images, no matter what the true content of the photo is ? Or I should strictly set a prompt for each image according to their specific contents?

**Comment by stefan-baumann** [comment]
If you're only dealing with photos of dogs, sure. Otherwise, I'd pass an empty prompt, or, if you're willing to put in some work, implement ODISE's approach. I would assume conditioning on a fundamentally wrong prompt should be worse than conditioning on an empty string.

**Comment by CoinCheung** [comment]
@stefan-baumann  Thanks !!!

**Comment by clf28** [comment]
Hi,
thank you for your brilliant work. May I ask how Distilled Text Conditioning was implemented in the Sec.B of supplementary?
